### ISSUE TITLE
What's the keywords and contentUrl in Ads object stand for?

### ISSUE THREAD

**Issue by ProgrammingLife** [AndriousSolutions/ads#11]
1. I've never faced with contentUrl and keywords tearms when showing admob ads. What does it mean?
2. How to be compliant with GDPR? If we don't have GDPR consent then we can't set the keywords, right? We just need to leave this field empty?
In pure java android we just need to do:
```
Bundle extras = new Bundle();
extras.putString("npa", "1");
AdRequest request = new AdRequest.Builder()
        .addNetworkExtrasBundle(AdMobAdapter.class, extras)
        .build();
```
How do I do this with firebase_admob plugin?

**Comment by Andrious** [comment]
The contentUrl and keywords are used by Admob to display 'ads' that relate to your app.
When using my Ads Dart package, you need not use them.

If you wish, you can explicitly supply a list of keywords using the keywords parameter. You are to enter keywords that would determine the 'type' of Ads you would like to see on your app.

In the contentUrl, you are to provide a URL for a website. Google with its many 'spiders' may have already scrapped that website for keywords and such. And so, Google will use those keywords to determine the 'type' of Ads you wished displayed on your app.

As to how to be compliant with GDPR. I am not up on that.
You and I both would have to research that.  :)

Greg

**Comment by oliverbytes** [comment]
> The contentUrl and keywords are used by Admob to display 'ads' that relate to your app.
> When using my Ads Dart package, you need not use them.
> 
> If you wish, you can explicitly supply a list of keywords using the keywords parameter. You are to enter keywords that would determine the 'type' of Ads you would like to see on your app.
> 
> In the contentUrl, you are to provide a URL for a website. Google with its many 'spiders' may have already scrapped that website for keywords and such. And so, Google will use those keywords to determine the 'type' of Ads you wished displayed on your app.
> 
> As to how to be compliant with GDPR. I am not up on that.
> You and I both would have to research that. :)
> 
> Greg

Question: for example, I have a feed in my app with links user clicks sometimes. For every user clicking the link, is it recommended to supply the url to the targeting info to get relevant ads in the future?

**Comment by Andrious** [comment]
I would recommend that, yes--only because the user may be interested in such websites in the future.

**Comment by oliverbytes** [comment]
> I would recommend that, yes--only because the user may be interested in such websites in the future.

Thank you. so it means it's naturally okay to supply the contentUrl multiple times during the app's session
