### ISSUE TITLE
Seems like ads.dart is not included in the package?

### ISSUE THREAD

**Issue by ProgrammingLife** [AndriousSolutions/ads#12]
I've just added firebase_admob dependency and when I try to do: **Ads ads;** - I get that I don't see ads.dart (https://github.com/AndriousSolutions/ads/blob/master/lib/ads.dart). Should I download it and place it to my lib folder manually or I have to import it in some other way?
I trying to follow this tutorial at the first page of this repo.

**Comment by ProgrammingLife** [comment]
Please explain me the example. Why we have to set two listeners for RewardedAds in two different places?
https://github.com/AndriousSolutions/ads/blob/master/example/main.dart#L274
https://github.com/AndriousSolutions/ads/blob/master/example/main.dart#L106

**Comment by ProgrammingLife** [comment]
I looked at firebase_admob-0.9.0+2 example and it completely different example from this repo's sample.
I see:
```
RaisedButton(
                  child: const Text('LOAD INTERSTITIAL'),
                  onPressed: () {
                    _interstitialAd?.dispose();
                    _interstitialAd = createInterstitialAd()..load();
                  },
                ),
                RaisedButton(
                  child: const Text('SHOW INTERSTITIAL'),
                  onPressed: () {
                    _interstitialAd?.show();
                  },
                ),
```
We should create new Interstitial instance for any time we want to load new ad? Or should I missed something?

**Comment by ProgrammingLife** [comment]
I looked at https://github.com/flutter/plugins/blob/master/packages/firebase_admob/example/lib/main.dart example:

```
                RaisedButton(
                  child: const Text('LOAD INTERSTITIAL'),
                  onPressed: () {
                    _interstitialAd?.dispose();
                    _interstitialAd = createInterstitialAd()..load();
                  },
                ),
                RaisedButton(
                  child: const Text('SHOW INTERSTITIAL'),
                  onPressed: () {
                    _interstitialAd?.show();
                  },
                ),
```
Should we actually create new instance any time we want to show new ad or we can just store one instance that we get from **createInterstitialAd()** and then just call **load()** only without creating new instance with:  **createInterstitialAd()..load();**?

**Comment by Andrious** [comment]
Hello there, Life.

Let's see if I can't get you on the right track.

"I've just added firebase_admob dependency and when I try to do: Ads ads;...."
- When using the Ads Dart package, it will 'add' the firebase_admob dependency for you.
https://pub.dev/packages/ads
This article will have more information:
https://medium.com/@greg.perry/add-ads-in-your-app-in-a-snap-a980d2050ef9

"Why we have to set two listeners for RewardedAds in two different places?..."
- You don't have to. The example merely demonstrates that you can. Two, three, any number of listeners can be assigned.

"Should we actually create new instance any time we want to show new ad..."
- Now you're looking at the firebase_admob plugin itself. Working with the Ads Dart package is a different story. You need only create one instance and 'show' and ad on each new screen. Again, turn to the article above for more info.

The Ads package is to make life easier. It talks to the plugin, not you.

Cheers.

Greg.
