### ISSUE TITLE
PlatformException(no_ad_for_id, dispose failed, no ad exists for id=972262985, null)

### ISSUE THREAD

**Issue by alexacz** [AndriousSolutions/ads#14]
The example code doesn't work when I run the app with **initOption 2 or 3**, like this:
`void main() {
  runApp(MyApp(initOption: 3));
}`

I've got the following exception:

> PlatformException(no_ad_for_id, dispose failed, no ad exists for id=972262985, null)

_id_ is different every startup

p.s.: **the following example works without any issue:**
`void main() {
  runApp(MyApp(initOption: 1));
}`

**Comment by Andrious** [comment]
Oh?  I'll give it a try.

**Comment by alexacz** [comment]
I've tested your example on iPhone 8
flutter doctor:
> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale en-CZ)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (not installed)
[✓] VS Code (version 1.36.1)
[✓] Connected device (2 available)

**Comment by Andrious** [comment]
I see what could cause the error you've encountered. Happens in certain circumstances, but as this is a library package, I'll make an effort to prevent the error at the very least.  Can't be blowing up other people's app, now can we!   Thanks.

**Comment by Andrious** [comment]
0.12.0 has been deployed. Those errors will continue because of the Beta plugin, but this Library package will now catch them and allow you to continue successfully.

**Comment by Andrious** [comment]
Hello there, Alexacz.   Has the issue now been fixed with the latest version?  How are things going?
