### ISSUE TITLE
Admob Mediation

### ISSUE THREAD

**Issue by glennmichaelmejias** [AndriousSolutions/ads#19]
How to setup mediation? Does it need to integrate sdk from ads network? Or do you have some ad network to recommend for admob mediation? Thanks.

**Comment by Andrious** [comment]
To get ads to your apps from multiple sources, you have to set up [Admob Mediation](https://www.google.com/search?q=%22admob+mediation%22&oq=%22admob+mediation%22&aqs=chrome..69i57j0l5.4166j0j7&sourceid=chrome&ie=UTF-8) in your [Admob account](https://apps.admob.com/). 

Please turn to the authors of the plugin, [firebase_admob](https://pub.dev/packages/firebase_admob), for further information as I don't see any such settings in the plugin itself.
