### ISSUE TITLE
iOS simulator?

### ISSUE THREAD

**Issue by sjmcdowall** [AndriousSolutions/ads#2]
I'm trying to get this to work on an iOS simulator but its not clear at all what to use for the testDeivce for this pooch.  I get the following in the log but using the value doesn't work:

<Google> To get test ads on this device, set: request.testDevices = @[ kGADSimulatorID ];

Is there a way to get the actual value of kGADSimulatorID from within Flutter?

**Comment by Andrious** [comment]
Whoa!  I don't have any experience with Ads in iOS.  Please, let us know what you find.  I'm trying to Google what that is in the first place!

**Comment by Andrious** [comment]
Would this give you any leads??

[To get test ads on this device, call: request.testDevices = [NSArray arrayWithObjects:GAD_SIMULATOR_ID, nil];](https://stackoverflow.com/questions/19527478/to-get-test-ads-on-this-device-call-request-testdevices-nsarray-arraywithob/39440671)

**Comment by sjmcdowall** [comment]
No -- but I did figure it out.  :) 

FWIW -- Within Flutter you need to pass in the exact string 'Simulator' as a test device for iOS Simulators to work ... Which winds up being the hidden constant kGADSimulatorID that you see everywhere that we should use .. but that constant isn't available within Flutter (that I can see) .. 

So I coded basically .. 

const String testDevice = '7A99777F0A314417895182B0CE153EEF';
const String testIOSSimulator = 'Simulator';

Then .. 

  static const MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
    testDevices:
        testDevice != null ? <String>[testDevice, testIOSSimulator] : null,
    keywords: <String>[
      'games',
      'esports',
      'competition',
      'social',
      'fortnite',
      'league of legends',
      'moba',
      'apex'
    ],
    contentUrl: 'https://metroesports.com',
    childDirected: false,
  );

And that did the trick ..

**Comment by Andrious** [comment]
And so, did you use the Ads package?

For example:

```
        Ads.setBannerAd(
          keywords: ['games',
          'esports',
          'competition',
          'social',
          'fortnite',
          'league of legends',
          'moba',
          'apex
          ],
          contentUrl: 'https://metroesports.com',
          childDirected: false,
          testDevices: testDevice != null ? [testDevice, testIOSSimulator] : null,
        );
```

**Comment by sjmcdowall** [comment]
That's the next step for the weekend!

Cheers

**Comment by Andrious** [comment]
> That's the next step for the weekend! Cheers
> […](#)

And so?  How did it go that weekend?   
Has the package worked for you?
