### ISSUE TITLE
the show local variable is shadowed in showBannerAd() (double declaration)

### ISSUE THREAD

**Issue by SirJohn2024** [AndriousSolutions/ads#21]
```
    bool show = false;
    // Can only have one instantiated Ads object.
    if (!_firstObject) return show;

    if (_bannerAd == null) {
      bool show = await setBannerAd(
```
should be:

```
    bool show = false;
    // Can only have one instantiated Ads object.
    if (!_firstObject) return show;

    if (_bannerAd == null) {
      show = await setBannerAd(

```

**Comment by Andrious** [comment]
Oh thanks!  I didn't realize. I'll look into it as soon as I can.

**Comment by Andrious** [comment]
Thanks again, Sergio.

You'll find the fix now in version, 1.5.1

**Comment by SirJohn2024** [comment]
I've tried the new version, and now, from time to time, I got no ad and this error logged on the logcat, even if showBannerAd returns ok:

`W/flutter: onAdFailedToLoad: 3
`

**Comment by Andrious** [comment]
I see. I'll see if it's the plugin itself, today.  Is this when repeatedly 'closed' and shown again and again?
Do you see 'any pattern' and or any clue as to why it fails to load from time to time?
Would you have an opinion as to the reason?

Regards.

**Comment by SirJohn2024** [comment]
It can be related to this: https://github.com/flutter/flutter/issues/28733
