### ISSUE TITLE
App is broken when I add the Ads 

### ISSUE THREAD

**Issue by cpatricio23** [AndriousSolutions/ads#23]
Hi guys can you help me with this? 
"firebase_admob-0.9.0+9/android/src/main/java/io/flutter/plugins/firebase admob/AdRequest Builder Factory.java uses or overrides a deprecated API."

After the app compiled it cant be open.

**Comment by Andrious** [comment]
Others have yet to experience such an issue. In my own tests, the app will always open.

The error  you're displaying refers to the plugin itself used by this library package.

I feel you may find a possible solution with the authors of the plugin, [firebase_admob](https://pub.dev/packages/firebase_admob).

Asking the same question with them may get you a helpful answer: [New Issue](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5B%3Cfirebase_admob%3E%5D+%3CTITLE%3E)

Possibly you're not the only one with such a problem, and has already been asked under [issues](https://www.google.com/search?ei=ZPXGXbrdAs69gge5lpPYAw&q=site%3Agithub.com%2FFirebaseExtended%2Fflutterfire%2Fissues+insubject%3A%22%5Bfirebase_admob%5D%22&oq=site%3Agithub.com%2FFirebaseExtended%2Fflutterfire%2Fissues+insubject%3A%22%5Bfirebase_admob%5D%22&gs_l=psy-ab.3...36652.36652..37905...0.0..0.112.112.0j1......0....2j1..gws-wiz.Gb2Z5r0A08o&ved=0ahUKEwi6n_fu0d3lAhXOnuAKHTnLBDsQ4dUDCAs&uact=5).
