### ISSUE TITLE
How to show video in round two ?

### ISSUE THREAD

**Issue by athlona64** [AndriousSolutions/ads#27]
first ads is show normally but when end ads and get rewards i'm click round two it not available to load ads

but i close app and open again it can watch

**Comment by athlona64** [comment]
sorry i'm write something wrong

**Comment by Andrious** [comment]
"it not available to load"  - Would you provide the 'error message' or log files please.

**Comment by athlona64** [comment]
it's show "An ad has loaded successfully in memory." in round two but can't open video ads

**Comment by Andrious** [comment]
I'm not experiencing such an issue. 
Have you been able to get the [example code](https://github.com/AndriousSolutions/ads/blob/d619f100cc92ab5f22e18948f17f640315582a0d/example/main.dart) to work? 
What tool are you using: Android Studio? 
Do you see anything in the Logcat?

**Comment by Andrious** [comment]
Is this still an issue?

**Comment by cjszk** [comment]
I'm having a similar issue. It appears to happen when the Widget unloads once.
When I use Navigator.push() or Navigator.pop() and come to revisit the page the ad does not load.
While the widget is loaded I can run the ad multiple times.

**Comment by cjszk** [comment]
I had a similar issue. It appears to happen when the Ads Widget provided by the library unloads once.
(I encountered this when I used Navigator.push() or Navigator.pop() and come to revisit the page the ad does not load).

Moving it to a static class and having the Ads instance static works.
The below code is a working solution using static instantiated Ad

```
import 'package:flutter/material.dart';
import 'dart:io' show Platform;
import 'package:firebase_admob/firebase_admob.dart';
import 'package:ads/ads.dart';

class AdProvider {
  static final String _appId = Platform.isAndroid
    ? ''
    : '';
        
  
  static final String _videoUnitId = Platform.isAndroid
    ? ''
    : '';


  static final String _bannerUnitId = Platform.isAndroid
      ? ''
      : '';

  static Ads _ads = Ads(_appId);
  
  /// Assign a listener.
  static MobileAdListener _eventListener = (MobileAdEvent event) {
    if (event == MobileAdEvent.clicked) {
      print("_eventListener: The opened ad is clicked on.");
    }
  };

  static void showBanner(
          {String adUnitId,
          AdSize size,
          List<String> keywords,
          String contentUrl,
          bool childDirected,
          List<String> testDevices,
          bool testing,
          MobileAdListener listener,
          State state,
          double anchorOffset,
          AnchorType anchorType}) =>
      _ads?.showBannerAd(
          adUnitId: adUnitId,
          size: size,
          keywords: keywords,
          contentUrl: contentUrl,
          childDirected: childDirected,
          testDevices: testDevices,
          testing: testing,
          listener: listener,
          state: state,
          anchorOffset: anchorOffset,
          anchorType: anchorType);

  static void hideBanner() => _ads?.closeBannerAd();

  /// Call this static function in your State object's initState() function.
  static void init() => _ads ??= Ads(
        _appId,
        bannerUnitId: _bannerUnitId,
        keywords: <String>['ibm', 'computers'],
        contentUrl: 'http://www.ibm.com',
        childDirected: false,
        testDevices: ['Samsung_Galaxy_SII_API_26:5554'],
        testing: false,
        listener: _eventListener,
      );

  /// Remember to call this in the State object's dispose() function.
  static void dispose() => _ads?.dispose();

  static showAd(eventListener) async {

    _ads.setVideoAd(
      adUnitId: _videoUnitId,
      keywords: ['fitness', 'supplements', 'diet', 'weight loss'],
      contentUrl: 'http://www.publang.org',
      childDirected: true,
      listener: eventListener 
    );

    _ads.showVideoAd();
    _ads.dispose();
  }
}
```

and invoke like so:

```
AdProvider.showAd((RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
   setState(() {
       adSeen = true;
    });
});
```

**Comment by Andrious** [comment]
Interesting. Merely placing the class in a static reference allows it to display a video a follow-up time??
You're providing the [Single Solution](https://medium.com/follow-flutter/my-apps-no-good-here-s-why-7699347bb235#2c8a) approach to the code.  Note, I'm not getting this problem in the first place, but I'll see what I can do to re-create the issue.
