### ISSUE TITLE
Ads already initiated

### ISSUE THREAD

**Issue by jsonpreet** [AndriousSolutions/ads#30]
If i use Ads ads and Ads() in multiple screens i got message.

[Ads()] An Ads class is already instantiated!

And if don't use Ads() function in screen i got error

**Comment by Andrious** [comment]
Indeed, you're not to call the constructor twice. 
If you need to show ads throughout your app, instantiate once but to a static variable or class property accessible throughout your app:  [A Single Solution](https://medium.com/@greg.perry/my-apps-no-good-here-s-why-7699347bb235#2c8a)

Lastly, be sure to have only the 'major' version number and then 0.0 in your pubspec.yaml.

``` 
dependencies:
  ads:^1.0.0
```
