### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView

### ISSUE THREAD

**Issue by athlona64** [AndriousSolutions/ads#31]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by Andrious** [comment]
The library package, ads, doesn't use the UIWebView.  Perhaps the Github forum can direct you to a probable solution: 
[ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs](https://github.com/flutter/flutter/issues/39470#issuecomment-600172320).
