### ISSUE TITLE
Cookie Issue

### ISSUE THREAD

**Issue by atarana** [AndriousSolutions/ads#32]
Hi, I'm using the plugin in my app and in iOS it works pretty well but in Android it shows this error:
`
W/Ads     (27286): JS: A cookie associated with a resource at http://doubleclick.net/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032. (https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318482078%2C318484497%2C318486317%2C318477280%2C318484676%2C318482460%2C318484801%2C318486847%2C318487060%2C318491267%2C318491793%2C318483611%2C318491480%2C318475417&format=interstitial_mb&heap_free=2425429&heap_max=201326592&heap_total=10540029&js=afma-sdk-a-v202006999.15301000.1&msid=app.facelove&preqs=7&request_pkg=io.flutter.plugins.firebaseadmob.MobileAd%24Interstitial&seq_num=8&target_api=28#caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318482078%252C318484497%252C318486317%252C318477280%252C318484676%252C318482460%252C318484801%252C318486847%252C318487060%252C318491267%252C318491793%252C318483611%252C318491480%252C318475417&format=interstitial_mb&heap_free=2425429&heap_max=201326592&heap_total=10540029&js=afma-sdk-a-v202006999.15301000.1&msid=app.facelove&preqs=7&request_pkg=io.flutter.plugins.firebaseadmob.MobileAd%2524Interstitial&seq_num=8&target_api=28:0)
I/chromium(27286): [INFO:CONSOLE(0)] "A cookie associated with a resource at http://doubleclick.net/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.", source: https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318482078%2C318484497%2C318486317%2C318477280%2C318484676%2C318482460%2C318484801%2C318486847%2C318487060%2C318491267%2C318491793%2C318483611%2C318491480%2C318475417&format=interstitial_mb&heap_free=2425429&heap_max=201326592&heap_total=10540029&js=afma-sdk-a-v202006999.15301000.1&msid=app.facelove&preqs=7&request_pkg=io.flutter.plugins.firebaseadmob.MobileAd%24Interstitial&seq_num=8&target_api=28#caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318482078%252C318484497%252C318486317%252C318477280%252C318484676%252C318482460%252C318484801%252C318486847%252C318487060%252C318491267%252C318491793%252C318483611%252C318491480%252C318475417&format=interstitial_mb&heap_free=2425429&heap_max=201326592&heap_total=10540029&js=afma-sdk-a-v202006999.15301000.1&msid=app.facelove&preqs=7&request_pkg=io.flutter.plugins.firebaseadmob.MobileAd%2524Interstitial&seq_num=8&target_api=28 (0)
`
Can you fix?

**Comment by Andrious** [comment]
Hello, atarana

The cause appears to be a new feature of the browser, Chrome as of July 14, 2020: https://www.chromestatus.com/feature/5633521622188032

I'm assuming your using a mobile phone with Chrome installed. 
I've not experienced this error myself. 
At this point, I don't see the error is coming from the Ads package. 

Let's test that, ok?
Please, would you uninstall Chrome or have the mobile app use another browser.
Let's see if it is indeed a problem involving the Chrome browser or not.

**Comment by atarana** [comment]
Hi and thanks for the reply.

I tried to disable chrome but it seems that the error is into the webview used in order to display the ads itself.

**Comment by Andrious** [comment]
Webview?  What is the circumstance before this error occurs?  
When does the error occur? 
Tell me a story as to what happens.  
My guess is yours is a video ad and the error occurs when the video is tapped on, yes?

Is this on a phone or a tablet?
