### ISSUE TITLE
Can't update firebase_core to version 0.5.0

### ISSUE THREAD

**Issue by alectogeek** [AndriousSolutions/ads#33]
Because ads 1.7.3 depends on firebase_admob ^0.9.0 and no versions of ads match >1.7.3 <2.0.0, ads ^1.7.3 requires firebase_admob ^0.9.0.

**Comment by Andrious** [comment]
One moment...   I'll take a look into this.

**Comment by Andrious** [comment]
Yes, many other packages and apps have been waiting for over a month now [for an update to the firebase_admob plugin](https://github.com/FirebaseExtended/flutterfire/issues/3340). There is a firebase_admob plugin currently under development with a version number, 0.10.0-dev.1.  The Ads package will use it, for now, to allow for firebase_core 0.5.0. This is until a 'production ready' version is made available to us.

**Comment by Andrious** [comment]
Please stand by...

**Comment by Andrious** [comment]
Ads ver. 2.0.0 is now available.  
Note, the firebase_admob plugin is still 'under development.'  
Please, let me know if there are any issues with this release.

**Comment by alectogeek** [comment]
@Andrious Thanks!
Looks like everything is ok for now. Thanks a lot!
