### ISSUE TITLE
Upgrade firebase_admob dependency to 0.11.0+1

### ISSUE THREAD

**Issue by alectogeek** [AndriousSolutions/ads#36]
There is an upgrade of all flutterFire packages

**Comment by Andrious** [comment]
ok.  I'm on it...

**Comment by Andrious** [comment]
Done!  Version: 2.2.0

Supplied a 'range' now:  firebase_admob: ">=0.10.0 <1.0.0"

This is done so we won't be interrupted by third-party 'upgrades' until there is a significant change that is no longer backward-compatible.  

That'll keep things going for a time I would think.

Thanks for letting me know.
