### ISSUE TITLE
Need clarification for Ad Unit ID

### ISSUE THREAD

**Issue by lab-nit-s** [AndriousSolutions/ads#4]
Hello, first of all, this is a great wrapper that you have written.

I have one confusion though. In the code below for `setBanner`

```dart
/// Set the Banner Ad options.
  static void setBannerAd({
    AdSize size = AdSize.banner,
    List<String> keywords,
    String contentUrl,
    bool childDirected,
    List<String> testDevices,
    AdEventListener listener,
  }) {
    var info = _targetInfo(
      keywords: keywords,
      contentUrl: contentUrl,
      childDirected: childDirected,
      testDevices: testDevices,
    );

    if (listener != null) banner._eventListeners.add(listener);

    _bannerAd = BannerAd(
      adUnitId: Ads.testing ? BannerAd.testAdUnitId : Ads._appId,
      size: size,
      targetingInfo: info,
      listener: banner._eventListener,
    );
  }
```

you are doing this
> adUnitId: Ads.testing ? BannerAd.testAdUnitId : Ads._appId,

if `testing is true` you are using `BannerAd.testAdUnitId` otherwise you are using the `_appId` that was providences in `Ads.init`

Should we not be using a different `BannerAdUnitID` instead of the `_appId`?. Or is it ok to use the ApID instead of adUnitID for production app ??

**Comment by Andrious** [comment]
Hi there.   I'll look into this and get back to you shortly.

**Comment by Andrious** [comment]
I'm not understanding this sentence,   ' Or is it ok to use the ApID instead of adUnitID for production app ??'

You are to use the _appId that was provided in Ads.init when in production.  Yes.
The code is correct.

I not certain of your statement, 'Should we not be using a different BannerAdUnitID instead of the _appId?'

Why would you use a different BannerAdUnitID instead of the _appId?

**Comment by lab-nit-s** [comment]
The App has an Admob id. The banner/interstitial/rewarded ads have their
own unit ids.

What I am saying is the the Id provided in init  is not a banner ad unit
id.

What we want to pass in setBanner is the BannerAdUnit id. Not the Admob App
id.

**Comment by Andrious** [comment]
I see the issue now. It will be addressed, today.

**Comment by Andrious** [comment]
Ads version [0.4.0](https://github.com/AndriousSolutions/ads/commit/af211952be575b711b318fcf328f401997e7c7e3#diff-37c77d95df56b4fbad99a519fa035ec6)  has addressed the recent requirement to supply a separate unit id per type of ad.
