### ISSUE TITLE
Application crashed

### ISSUE THREAD

**Issue by sabdelhay** [AndriousSolutions/ads#8]
Hello,
Thank you for sharing this package, but when I used it the application crashed at the step of installing the app.
I would appreciate your help with this issue.

Thank you,

**Comment by Andrious** [comment]
Yes, I can help.  Please present the line of code you used to install, and more importantly, provide me with the error message when the application 'crashed.'

**Comment by SaadArdati** [comment]
I can elaborate. It's a common issue with the base admob package.

Here's an issue on another admob utility package that has the exact same description as well as what I'm current stuck on right now: https://github.com/kmcgill88/admob_flutter/issues/79

**Comment by Andrious** [comment]
@SwissCheese5   Are you using latest version of [Ads](https://pub.dev/packages/ads)?  The latest version catches errors now. Please, give me a logcat of the error.

**Comment by SaadArdati** [comment]
It's not a problem with your package, it's a problem with the base admobs package and that isn't able to throw an error either. it just gets stuck installing. I'll see if I can provide more info later but it's unlikely
